### ISSUE TITLE
Add to fluidd config to ignore Pending changes prompt for bed_tilt_calibrate like bed_mesh is currently

### ISSUE THREAD

**Issue by DaVinci-10** [fluidd-core/fluidd#1210]
### Is your feature request related to a problem? Please describe

Would it possible to add the bed_tilt_calibrate to a list of save_config ignore messages like
`Ignore default bed mesh Pending Configuration Changes`

As I have it run before each print, It would be helpful to ignore the prompt to save like bed_mesh.
![image](https://github.com/fluidd-core/fluidd/assets/1100376/c5a44658-b1b9-4247-a504-57d25393b5ff)

### Describe the solution you'd like

Add another slider or have the same one apply to both
![image](https://github.com/fluidd-core/fluidd/assets/1100376/55d439e5-604e-4257-9b39-52c26f8498ff)

### Describe alternatives you've considered

Right now I just restart to not save.

**Comment by pedrolamas** [comment]
Hi @DaVinci-10, thanks for opening this Feature Request.

I see value in this, and we will indeed implement this.

Having said that, I am considering if we should instead add a customizable area to specify sections to ignore, instead of just adding yet another toggle switch...

It would look something like this:

![image](https://github.com/fluidd-core/fluidd/assets/85504/8910057a-2d66-4908-b7f2-4b9fa9c9ba0d)

@matmen, any thoughts on this?

**Comment by matmen** [comment]
@pedrolamas I think that's a good idea, not sure if it should be a multi-select with a predefined list of sections or if it should be freely configurable by the user - but I guess the latter provides more flexibility
