### ISSUE TITLE
Button to copy bed mesh into clipboard as image

### ISSUE THREAD

**Issue by WayneManion** [fluidd-core/fluidd#1216]
### Is your feature request related to a problem? Please describe

Getting a good bed mesh is an important part of 3D printing. Many questions about Klipper involve this critical subject. Fluidd presents the bed mesh to the user with a neat 3D interface, but there isn't a great way to share this with others when seeking help. I think the current solution for most is to take a screen shot of the bed mesh and share it. 

### Describe the solution you'd like

I think it would be great if the bed mesh section of Fluidd's Tuning page had a button the user could click to copy the bed mesh into their clipboard. Ideally this would also include a section at the bottom with the variance, the current bed mesh display options (wire frame, show flat plane, etc) and possibly the bed temperature when the mesh was captured.

**Comment by pedrolamas** [comment]
Hi @WayneManion, thank you for sending this Feature Request.

This is something we can take a look but be aware that Clipboard access is something that sometimes is not possible programmatically due to security concerns (although I believe it should be fine to write to it, which is the case here).

Nevertheless, the easy way out right now would be to take a screenshot of the area you want!
