### ISSUE TITLE
FR: push/browser notifications

### ISSUE THREAD

**Issue by imrcly** [fluidd-core/fluidd#129]
Browser notification when a print completes/*error stops*

Tried to find this in vueify for desktop browser but did find it as an html standard https://developer.mozilla.org/en-US/docs/Web/API/Notification
and as a  push notification view for vue on mobile devices https://vuejsexamples.com/a-library-for-previewing-push-notification-with-vue/

**Comment by cadriel** [comment]
I've been hesitant to implement this in the past, due to a lot of users usually blocking browser based notifications - or them not being well integrated with the OS.

**Comment by jtkDvlp** [comment]
It would be nice to get notifications on mobile via **P**rogressive **W**eb **A**pp design

**Comment by cadriel** [comment]
Fluidd is already a PWA. The notifications themselves are another story.. I'll look into them a bit more in an upcoming update.

**Comment by jtkDvlp** [comment]
If desired please give a little developer overivew / intro documentation and I offer my help :-)

**Comment by matmen** [comment]
I've started implementing this, but we are running into a couple issues here:
- [Chrome](https://groups.google.com/a/chromium.org/g/Blink-dev/c/IVgkxkRNtMo) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1429432) no longer allow notifications to be instantiated from insecure origins (meaning only HTTPS is supported)
- To support secure origins, Moonraker will have to be served over HTTPS too to prevent mixed content
- I believe audio cues (as suggested in #520) also won't work because playing sound requires user interaction

Because of those reasons, deploying this is currently blocked (as it would only work for localhost or setups with both Fluidd and Moonraker being served over HTTPS). I'll move this to the backlog and keep you updated if anything changes.

**Comment by pedrolamas** [comment]
Given the technical requirements for in-browser notifications to work (specifically, HTTPS), I don't see this moving forward anytime soon.

I would recommend that instead, users just use the existing Moonraker notifier support: https://moonraker.readthedocs.io/en/latest/configuration/#notifier
