### ISSUE TITLE
Reuse of recently printed filename results in incorrect print details

### ISSUE THREAD

**Issue by deltafactory** [fluidd-core/fluidd#1401]
### Fluidd Version

v1.18.2-7b9f0c3

### Browser

Firefox

### Device

Laptop

### Operating System

Windows

### What happened

I uploaded a gcode file but needed to correct some slicer parameters after starting/cancelling the job. After reuploading the new gcode with the same filename the details in the Printing panel were incorrect.

### What did you expect to happen

I expected the projected print time, preview image, and percent completed to reflect the new file's data.

### How to reproduce

1. Upload gcode and start print job.
2. Replace file with different gcode using the same filename,
3. Start print job.

### Additional information

On a hunch that it was browser cache related, I hit shift-refresh. All issues were addressed.

**Comment by pedrolamas** [comment]
Hi @deltafactory, thank you for opening this issue.

However, I have been unable to reproduce this issue in the latest Fluidd 1.30, so my advice is that you update to it from the version you are currently using.

---

It should also be noted that Creality has repeatedly taken open-source code (such as Klipper, Moonraker, Fluidd, Mainsail, KlipperScreen), modified it, and used it in their printers without releasing the changes, thereby violating the open-source licenses. This issue was observed with their Sonic Pad and continues to be evident in other Creality products today.

No one in the Fluidd dev team is being paid for the work we are doing here, but the very least we expect is for everyone to respect the licenses we put in place.

As such, any support related to Creality printers should be entirely directed to Creality themselves.
