### ISSUE TITLE
Fix fan behavior with Danger Klipper

### ISSUE THREAD

**Issue by fbeauKmi** [fluidd-core/fluidd#1457]
### Is your feature request related to a problem? Please describe

There is a different behavior of fan.py between klipper and danger-klipper.
klipper scales input between 0 and max_power and report ``pwm`` as ``speed``
[set_speed in klipper](https://github.com/Klipper3d/klipper/blob/a19d64febdbaa7d5ec0a0912bb65c6547c370ec3/klippy/extras/fan.py#L48-L67)

danger-klipper scales input between min_power and max_power and report ``input value`` as ``speed``
[set_speed in danger-klipper](https://github.com/DangerKlippers/danger-klipper/blob/2b6bd6562ee6648a8460cb22061a40956ffc40c8/klippy/extras/fan.py#L81-L109)
For now, while using Danger-klipper, the display value in fluidd is inaccurate while using min_power/max_power, sliders gives unwanted behavior. 

### Describe the solution you'd like

As support to DK in Fluidd was recently added.
Proposal : while using DK, do not scale fan.speed value, I guess it is this lines
https://github.com/fluidd-core/fluidd/blob/37617b517c8c932a003c8543684f54e76006054f/src/components/widgets/outputs/OutputFan.vue#L60

Thanks,

**Comment by pedrolamas** [comment]
Hi @fbeauKmi, thank you for sending this feature request.

Ideally the existing Klipper API surface & format should not change in Danger Klipper as that will lead to breaking expected behavior and eventually introduce issues in Fluidd, Mainsail, KlipperScreen and other UIs - which is what we are seeing here.

The rule of thumb is to not change existing endpoints/property naming or data formats in the Klipper API, but instead add new endpoints and/or properties that will enrich the existing API.

We will coordinate this matter with the Danger Klipper development team and update this ticket accordingly, but I am hoping that we will not need to do any changes in Fluidd side.
