### ISSUE TITLE
Thermals Power % Graph Line Colors not in Legend

### ISSUE THREAD

**Issue by blackadar** [fluidd-core/fluidd#1462]
### Fluidd Version

1.30.1

### Browser

Chrome

### Device

Desktop PC

### Operating System

Linux

### What happened

The Thermals graph legend which displays when hovering over the graph does not display a color corresponding to the lines for Power % when enabled by clicking the column above the graph:

![image](https://github.com/fluidd-core/fluidd/assets/20449792/557e823c-b778-4a44-8b22-d02f516f51c5)

### What did you expect to happen

I was confused as to what those lines were representing until I discovered you could enable/disable them by clicking the Power % values in the table above the graph. I expected that, when new lines were added, I would see their color and label in the legend while hovering over the graph.

### How to reproduce

1. Click the Power% value for any thermal data to enable its line on the graph.
2. Hover over the graph, and note that the new line color is not in the legend.

**Comment by pedrolamas** [comment]
Hi @blackadar, thank you for reporting this issue.

I believe the problem here is actually that we have a bug on the colors used: the graph should be using the same color for extruder temperature AND power (so the legend would make sense as it is right now), but seems we are using a different color for extruder power.
