### ISSUE TITLE
Exclude Region

### ISSUE THREAD

**Issue by lar3ry** [fluidd-core/fluidd#359]
## Thank you for using fluidd!

Nono! Thank YOU  for all your hard work!

## Is your feature request related to a problem? Please describe.
The main plugin I miss from my Octoprint/Klipper days is the "exclude region" one.

## Describe the solution you'd like:
I'd like to see it implemented as part of the GCode Preview box,.

## Describe alternatives you've considered:
There are no alternatives that I know of.

## Affected users and/or setups:
Users that have ever had a print consisting of many objects, and had one get messed up, will love you for it.

**Comment by StuSerious** [comment]
hey there @lar3ry!

the option to exclude regions of gcode has been in talks since day one of the gCode preview.
with that still being in BETA, I think the focus will be on first polishing the preview to add onto it going forward!

so the cancel object / cancel area feature is in the pipeline, but we have no ETA for it yet!
thank you for your feature suggestion, have a great day!
~S

**Comment by troy-jacobson** [comment]
Hi, there has been a lot of work being done for this feature outside of Fluid for a while now.  The dependencies in Moonraker are available.  A pull requrest for Klipper is is open and near approval.  As a member of a group working on this feature, I've been working with personal modified fluidd branch with a working implementation.  As soon as I get some of the Klipper changes moving along, I'll be creating a pull request with my changes.

I don't think my changes are ready as is.  I'm more of a back end developer.  The UX could use some help, but the logic is solid.  I've been using my chnages since last fall with no issues.  I would have posted them earlier, but with the unfortunate state of Fluidd dev for a while, I didn't make it a priority.  But now that things are up and running again, I'll get it to you as soon as possible.

For those interested, Klipper, obviously, takes care of the low-level functionality.  There is a preprocessor in Moonraker that takes uploaded gcode files and tweaks them based on the slicer dialect so there is a uniform structure for Klipper that is not slicer dependent.

For a UI like fluidd, it gets all the information needed from the Klipper status.  Although I'm drawing the part outlines on the above mentioned gcode previewer, that is not necessary for this to function, nor are there any changes needed to Fluidd's gcode parser.

**Comment by matmen** [comment]
waiting for upstream: Klipper3d/klipper#4716

**Comment by hany** [comment]
Looks like the klipper functionality was merged yesterday. Looking forward to having this integrated into Fluidd.

**Comment by matmen** [comment]
@troy-jacobson Hey, I just looked at your UI implementation and it looks very promising! Just wondering what the current state of it is? I'm happy to help with refactoring it a bit if that's still needed :)

**Comment by pedrolamas** [comment]
I've been testing @troy-jacobson branch changes (thank you, btw!!) with the latest Klipper and Moonraker, and this seems to work very well!!

![image](https://user-images.githubusercontent.com/85504/174485873-99599e73-9b00-4f0c-81b7-1830372fdf9b.png)

Might need some minor fixes and code reformatting, but overall it should be fine to get this over the line! 😁

**Comment by matmen** [comment]
Hey @kageurufu, I just noticed you said (in https://github.com/Klipper3d/klipper/pull/5413#issue-1202631422) that Troy was busy and you had Fluidd code you are going to submit. Is this still the plan? Big fan of this feature and would love to have this land in 1.19. Happy to help if it still needs a bit of refactoring. Big thanks for your work!

**Comment by matmen** [comment]
@kageurufu Any news yet? We would love to land this in 1.19, which is scheduled for this sunday. Just need either your approval so we can merge this, or you to create your own PR (probably easier license and sign-off wise) 😉 Let me know if you have any questions or need help with anything

**Comment by kageurufu** [comment]
Ooh my bad. I'll create a PR if it makes the licensing easier :)

**Comment by troy-jacobson** [comment]
Hi everyone,  sorry for being kind of absent on this.  I forgot these changes were out there.  Kageurufu's repo has a better change of being up-to-date since I've been running the same version for months now and my last attempt to merge didn't go well.  I can dust things off to help if needed.

If either of you have a branch or pull request ready to go, I'd be more than happy to add whatever sign-offs are needed.

My main "concern" is with usability.  I didn't come up with a good way to point a user to how to use the UI to cancel an object.  I just kind of knew how to do it.  Otherwise, its been working without issues for a long time now.

**Comment by kageurufu** [comment]
I'm working on a rebased branch, then i'll do another branch with it squashed for the PR

**Comment by jlsjonas** [comment]
Sorry to poke in a completed issue but would anyone be up to extending the functionality to _regions_, not just objects? That way big prints would also be covered (for the several cases you can recover most of the single-object print & fix it later)
Willing to _take the lead_ but fairly new to klipper's code & want to make sure it would be something that would be accepted across the different projects.

Thanks for your time!

**Comment by pedrolamas** [comment]
@jlsjonas there is no work done to add Regions Exclusion, but it is something we would be interested in integrating, yes! 🙂

**Comment by jlsjonas** [comment]
@pedrolamas I already peeked at the klipper code for excluding objects and it seems to luckily be implemented in a way that should allow us to reuse it for regions
Will see what I can do when I got some spare time!

**Comment by troy-jacobson** [comment]
@jlsjonas I think there is a fairly good chance that the current code could support regions in a straightforward way, but the success would be dependent on what gcode the various slicers generate on each side of the transitions.  There may need to be some limitations, such as not crossing a boundary while extruding.

Also, I think there would be some interesting work needed on the various UIs to generate decent region coordinates to pass to klipper and possibly check that region is compatible with any limitations there may be.

Feel free to drop me an email or DM in discord and we can chat.

**Comment by kageurufu** [comment]
Same, if you want to open a discord chat, feel free to add kageurufu#9003,
or ping us both in the Voron server (#klipper channel probably). I've got
some rough draft of exclude object v2 already, that skips through excluded
sections of the gcode directly to limit overhead

**Comment by cryptospook86** [comment]
This feature just saved my bacon. Thank you guys for all your hard work!
