### ISSUE TITLE
Select/Copy/Paste doesn't work on iOS when editing config files

### ISSUE THREAD

**Issue by russiancatfood** [fluidd-core/fluidd#380]
Latest Fluidd build won't let me select/copy/paste bits of config when using the build-in editor.

This worked in earlier builds, before the more fancy VCCode style editor was added.

**Comment by StuSerious** [comment]
hey there @russiancatfood!

thanks for pointing that out! 
sadly there is not much that can be done about this bug, since it's not caused by fluidd. 
we are going to have to wait for upstream fixes before we can do anything..

I'll ping you here and let you know when that changes, it will also defenetely be in the fluidd release changelog when they manage to fix it :P

Cheers!
_~S_

**Comment by russiancatfood** [comment]
Thank you!
I figured, but I didn't know where to file it :)

Looking forward to getting this to work again. I seem to be one of the few mad men doing initial printer bring-up using a phone.

**Comment by matmen** [comment]
Hey, according to the [webkit bug tracker](https://bugs.webkit.org/show_bug.cgi?id=210071) this should have been solved with iOS 14.5, can you confirm?

**Comment by susisstrolch** [comment]
@matmen it neither works on iPad OS 15.3 nor iPhone OS 15.3. 
Also the cursor move by space key doesn’t work.
