### ISSUE TITLE
Average Speed & Flow Rates

### ISSUE THREAD

**Issue by pacmac** [fluidd-core/fluidd#394]
As per the subject, it would be very nice to be able to see the average speed and flow rates next to the current live values.

**Comment by matmen** [comment]
Hey! I'm happy to implement this, but just checking: could you clarify what this would be useful for? Asking because it's relatively trivial to calculate these based on print time and used filament (at least for the flow rate, average speed would be a different story). Is this just for stats, or is there another reason behind it?
