### ISSUE TITLE
Feature request: User specific layouts

### ISSUE THREAD

**Issue by OneMoreByte** [fluidd-core/fluidd#410]
## Is your feature request related to a problem? Please describe.
I use fluidd on both on a phone right next to my printer and my desktop. I don't want the camera and some other things visible on the phone. I created users expecting the layout to be specific to a user but updating the layout as `User1` also updated it for `User2`

## Describe the solution you'd like:
`User1` and `User2` have independent layouts when they log in. 

## Describe alternatives you've considered:
Layouts that are per device, maybe the settings could be saved on each machine.

## Affected users and/or setups:
I'm not sure who would benefit from this. I imagine its a weird edge case thing for _some_ people with multiple devices or for multi-user setups.

**Comment by bulbersator** [comment]
I am in the same situation. I think the big advantage of Fluidd is that you can just use an old phone as a screen next to the printer, instead of buying and configuring a new screen for RPI. I think the most common way of working with Fluidd involves a desktop computer for the main setup and a phone / tablet as the screen next to the printer. Therefore, it would be very useful to be able to set the page layout for a user or a device.

**Comment by matmen** [comment]
Related: #370
