### ISSUE TITLE
Fullscreen Camera View not respecting Settings

### ISSUE THREAD

**Issue by Durahl** [fluidd-core/fluidd#542]
### What happened

Greetings!

[Due to how I mount my Camera in my Frame](https://i.imgur.com/3NKCEuY.jpg) I need _both_ Camera Axis flipped for the Camera View to match what I'd see standing in front of the machine.

The settings allow for such an adjustment and the Regular Camera View respects that setting but the Fullscreen Camera View does not.

### What did you expect to happen

I'd expect the Fullscreen Camera View to also be respecting the in the Camera Settings made changes.

### How to reproduce

Set up a Camera and in the Camera Settings have one **or** the other **or** both Camera Axis flipped:
The Regular Camera Module **will** respect those changes.
The Fullscreen Camera View **will not** respect those changes.

### Additional information

Nuffin...

**Comment by matmen** [comment]
The fullscreen camera feed only opens the raw stream in a new tab at the moment, we can't change the orientation for that. We can however implement it for the "embedded" full screen view, most likely coming soon (for reference: https://github.com/fluidd-core/fluidd/issues/279#issuecomment-1046342209)

**Comment by matthewlloyd** [comment]
Until then, another option to edit your mjpg_streamer command line options (assuming you're using it - the standard OctoPi, FluiddPi, MainsailOS etc. distributions all do) so that the transformation you need is applied directly at the source. The `-hf` option can apply horizontal flip, `-vf` vertical flip, and the `-rot` option rotation `0-359` degrees: https://github.com/jacksonliam/mjpg-streamer/blob/master/mjpg-streamer-experimental/plugins/input_uvc/README.md

For example if your mjpg_streamer command line looks like this:

`mjpg_streamer -i 'input_uvc.so [options]' ...`

You could change it to:

`mjpg_streamer -i 'input_uvc.so -hf -vf [options]' ...`

**Comment by Durahl** [comment]
Where exactly would that command line have to be edited?
It doesn't appear to be part of the `webcam.txt` found in **FluiddOS** 🤔

**Comment by matthewlloyd** [comment]
@Durahl I don't use FluiddPi but I think you can add uncomment `camera_usb_options` in `/home/pi/klipper_config/webcam.txt` and add the options there:

https://github.com/fluidd-core/FluiddPI/blob/master/src/modules/mjpgstreamer/filesystem/home/pi/klipper_config/webcam.txt

**Comment by Durahl** [comment]
@matthewlloyd Yea, I was already experimenting with that line but without success...
I tried positioning the -vf -hf in various positions of the code without success - Any suggestions what I'm doing wrong?

**Comment by matthewlloyd** [comment]
The -hf and -vf probably need to go inside the quotes:

camera_usb_options="-r 2560x1440 -f 60 -hf -vf"

**Comment by Durahl** [comment]
@matthewlloyd Nope, doesn't work - The Fullscreen View ignores _that_ setting too =)
