### ISSUE TITLE
Why fluidd?

### ISSUE THREAD

**Issue by tinkerbeast** [fluidd-core/fluidd#759]
### Fluidd Version

0.0.1

### Browser

Firefox

### Device

Desktop PC

### Operating System

Linux

### What happened

This is a documentation bug. Not an issue.

### What did you expect to happen

N/A.

### How to reproduce

N/A

### Additional information

I was wondering why fluidd was created despite Mainsail being present. Is there something fundamentally different that Mainsail or fluidd tries to achieve? (Like maybe fluidd is meant for more than just support Klipper?)

I just want to understand why fluidd was created (about 10 months after Mainsail project).

If this was just a thing about two competing products, I wouldn't generally ask. However even in fluidd's main README file there's mention of MainSail - "Ray for [MainsailOS](https://github.com/raymondh2/MainsailOS)".

So why create a competing product, knowing full well that there is an existing product you can contribute to? Am I missing something here? Essentially I want to know if there is any fundamental philosophy different in what fluidd wants to achieve over MainSail.

**Comment by matmen** [comment]
Both Fluidd and Mainsail are web interfaces solely for Klipper (/Moonraker), it's just two different approaches of development. IMO it's always best to have "competition" in order to boost development and quality - as both interfaces are part of the Klipper community, it's not really competition, though. The Fluidd and Mainsail team work together in some aspects (as you already noticed yourself); for example FluiddPi is a fork of MainsailOS.
Sure, if the Fluidd team worked on Mainsail instead, development might get faster, but there would also be no alternatives or other approaches of solving problems, either.
