### ISSUE TITLE
Sortable Fluidd instances on right side

### ISSUE THREAD

**Issue by fuganater** [fluidd-core/fluidd#941]
### Is your feature request related to a problem? Please describe

Request the ability to sort Fluidd instances. 

### Describe the solution you'd like

Add the ability to sort Fluidd instances by either name, IP or manually. Manual could be the ability to drag them into the order you want. 
![fluidd](https://user-images.githubusercontent.com/64492697/200163793-0555e78d-4c9a-4dce-bae4-3882da53e7d8.png)

**Comment by pedrolamas** [comment]
From what I can see, there is no way to retrieve the IP address from the client side, so that is a no-go (the multi-instance is a client feature, so there is no expectancy for Moonraker adding such functionality!)

I will make a small change so that it will sort the instances alphabetically by name, keeping the active one on top.
